services:
  db:
    image: postgres:17
    container_name: game_tracker_db
    environment:
      POSTGRES_DB: game_tracker
      POSTGRES_USER: game_tracker
      POSTGRES_PASSWORD: game_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata_production:/var/lib/postgresql/data

volumes:
  pgdata_production:
    name: game_tracker_database