spring:
  application:
    name: GameTracker
  jpa:
    show-sql: true
    generate-dll: false
    database: POSTGRESQL
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

igdb:
  client-id: ${IGDB_CLIENT_ID}
  client-secret: ${IGDB_CLIENT_SECRET}