server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: GameTracker

  jpa:
    defer-datasource-initialization: true
    database: POSTGRESQL

  datasource:
    driver-class-name: org.postgresql.Driver

app:
  security:
    admin-emails: ${ADMIN_EMAILS:}
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
    token:
      jwt:
        rsa:
          private-key: classpath:keys/private.pem
          public-key: classpath:keys/public.pem
  igdb:
    client-id: ${IGDB_CLIENT_ID}
    client-secret: ${IGDB_CLIENT_SECRET}


logging:
  # Ruta donde se guardar√°n los logs
  file:
    name: logs/gametracker.log
    max-size: 10MB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %5p %class{0}:: %m%n"