spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

app:
  security:
    token:
      refresh:
        expires-in-days: 30
      jwt:
        with-user: ${JWT_ISSUER}
        expires-in-minutes: 15

logging:
  level:
    root: INFO
    com.nsteuerber.gametracker: INFO
    org.hibernate: WARN # Solo errores de base de datos
    org.springframework: WARN

  file:
    max-history: 5